apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: okteto-httpd-test
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: '/'
            backend:
              serviceName: okteto-httpd-test
              servicePort: 80
