apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: okteto-httpd-test
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: '/'
            backend:
              service:
                name: okteto-httpd-test
                port: 80
