name: Okteto Deployment
run-name: ${{ github.actor }} is testing out Okteto Deployments via GitHub Actions 🚀
on: [push]
jobs:
  okteto-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: 'Activate Namespace'
        uses: okteto/namespace@latest
        with:
          namespace: officialmkl
      - name: 'Build'
        uses: okteto/build@latest
        with:
          file: okteto-pipeline.yml
      - name: 'Trigger the pipeline'
        uses: okteto/pipeline@latest
        with:
          name: okteto-httpd-test
          filename: okteto-pipeline.yml
